=== GregoryQ/Homework-1-Internet-Programing/textbook.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="class">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="textbookslist">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="book" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="tittle" />
                                        <xs:element name="author" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="firstname" />
                                                    <xs:element type="xs:string" name="lastname" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="publisher" />
                                        <xs:element type="xs:string" name="website" />
                                        <xs:element type="xs:short" name="publication" />
                                        <xs:element type="xs:string" name="ISBN" />
                                        <xs:element type="xs:byte" name="edition" />
                                        <xs:element type="xs:string" name="cover" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GregoryQ/Homework-1-Internet-Programing/textbooks.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="textbook.xsl" type="text/xsl"?>
<class>
    <textbookslist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="textbook.xsd">
        <book>
            <tittle>Operating System Concepts</tittle>
            <author>
                <firstname>Abraham</firstname>
                <lastname>Silberschatz</lastname>
            </author>
            <author>
                <firstname>Peter</firstname>
                <lastname>Galvin</lastname>
            </author>
            <author>
                <firstname>Greg</firstname>
                <lastname>Gagne</lastname>
            </author>
            <publisher>Jonh Wiley and sons</publisher>
            <website>https://www.wiley.com/en-us</website>
            <publication>2012</publication>
            <ISBN>978-1-118-06333-0</ISBN>
            <edition>9</edition>
            <cover>hardcover</cover>
        </book>
        <book>
            <tittle>Computer Organization and Design: The Hardware/Software Interface.</tittle>
            <author>
                <firstname>David</firstname>
                <lastname>Patterson</lastname>
            </author>
            <author>
                <firstname>John</firstname>
                <lastname>Hennessy,</lastname>
            </author>
            <publisher>MorganKaufmann Publishers</publisher>
            <website>https://www.elsevier.com/books-and-journals/morgan-kaufmann</website>
            <publication>2013</publication>
            <ISBN>9783827415950</ISBN>
            <edition>5</edition>
            <cover>hardcover</cover>
        </book>
    </textbookslist>
</class>
